name: muslim
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  provider: ^6.0.2
  connectivity: ^3.0.6
  progress_indicators: ^1.0.0
  flutter_neumorphic: ^3.2.0
  geocoding: ^2.0.1
  http: ^0.13.4
  intl: ^0.17.0
  sqflite: ^2.0.1
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.17
  vibration: ^1.7.4-nullsafety.0
  sticky_headers: ^0.2.0
  scrollable_positioned_list: ^0.2.3
  rflutter_alert: ^2.0.4
  flutter_qiblah: ^2.0.2
  flutter_svg: ^1.0.0
  google_maps_flutter: ^2.1.1
  audio_video_progress_bar: ^0.10.0
  just_audio: ^0.9.18
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  card_swiper: ^2.0.1
  charts_flutter: ^0.12.0
  permission_handler: ^8.3.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Uthmanic
      fonts:
        - asset: asset/font/UthmanicHafs1Ver09.otf
    - family: Indonesia
      fonts:
        - asset: asset/font/Indonesia.otf
    - family: Basmalah
      fonts:
        - asset: asset/font/Basmalah.ttf
    - family: WeatherIcons
      fonts:
        - asset: asset/font/weathericons.ttf

  assets:
  # database
    - db/quran.db
  # image png
    - asset/pic/
  # image surat
    - asset/surat/
  # icon app
    - asset/icon/
